---
title: "Big Data and Global Surgery review"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
library(plotly)
load("02_country_summary.rda")
load("02_alldata.rda")
load("04_myworldmap.rda")


myplotdata = mydata %>% 
	mutate(dummy = 1) %>% 
	group_by(year) %>% 
	arrange(n_studytotal) %>% 
	mutate(nth_study = cumsum(dummy)) %>% 
	mutate(n_studytotal.groups = cut(n_studytotal,
																	 breaks = c(300, 500, 1000, 2000, 5000, 10000, 428346)) %>% 
				 	fct_recode("300-500"        = "(300,500]",
				 						 "500-1,000"      = "(500,1e+03]",
				 						 "1000-2000"      = "(1e+03,2e+03]",
				 						 "2,000-5,000"    = "(2e+03,5e+03]",
				 						 "5,000-10,000"   = "(5e+03,1e+04]",
				 						 "10,000-42,8346" = "(1e+04,4.28e+05]")) %>% 
	mutate(info = paste0(surgical_speciality, ": ", n_studytotal %>% formatC(format = "f", big.mark = ",", digits = 0), " patients"))
	
annual_summary = myplotdata %>%
	group_by(year) %>%
	summarise(n_year = sum(n_country), y_location = max(nth_study)+1)


```

### Number of patients per country

```{r}

mycols = RColorBrewer::brewer.pal(9, 'PuRd')[4:9]

mapdata %>% 
  ggplot(aes(x=long, y = lat, group = group, fill = n_country %>% cut(breaks = c(0, 3, 100, 500, 1000, 5000, 10000, 428346)))) +
  geom_polygon(colour = "black") +
  #theme_void() +
  coord_map("moll") +
  ggthemes::theme_map() +
  theme(legend.position = "bottom",
        #legend.justification = 'center',
        legend.text = element_text(size=10, face='bold'),
        legend.title = element_blank(),
        plot.caption = element_text(size=9, face='bold'),
        plot.title   = element_text(size=12))+
  guides(fill=guide_legend(ncol=2, reverse=TRUE)) +
	scale_fill_viridis_d(na.value = NA)


```



### Studies each year, coloured by N patients

```{r}


	
p1 = myplotdata %>% 	
	ggplot(aes(x = year)) +
	#geom_col(colour = "blue", fill = NA) +
	geom_point(aes(y = nth_study, fill = n_studytotal.groups, text = info), shape = 21, size = 4) +
	theme_classic() +
	geom_text(data = annual_summary, aes(y = -0.2, label = n_year %>% formatC(format = "f", big.mark = ",", digits = 0)), hjust = -0.3) +
	coord_flip() +
	scale_x_continuous(breaks = 2007:2018) +
	scale_y_continuous("Studies each year", limits = c(-0.2, 27)) +
	scale_fill_viridis_d("N patients", direction = -1) +
	theme(legend.position = "top")


ggplotly(p1, tooltip = c("text"))

```




### Studies each year, coloured by surgical specialty

```{r}

p2 = myplotdata %>% 	
	ggplot(aes(x = year)) +
	#geom_col(colour = "blue", fill = NA) +
	geom_point(aes(y = nth_study, fill = surgical_speciality, text = info), shape = 21, size = 4) +
	theme_classic() +
	geom_text(data = annual_summary, aes(y = -0.2, label = n_year %>% formatC(format = "f", big.mark = ",", digits = 0)), hjust = -0.3) +
	coord_flip() +
	scale_x_continuous(breaks = 2007:2018) +
	scale_y_continuous("Studies each year", limits = c(-0.2, 27)) +
	scale_fill_brewer("N patients", palette = "Paired", direction = -1) +
	theme(legend.position = "top")


ggplotly(p2, tooltip = c("text"))

```


